/** GAS constants mirrored from Codice.js / iscrizioni.js */

const SPREADSHEET_ID =
  process.env.SPREADSHEET_ID || '1vwyCTqXJDe0IKr_tIH2Dgz5ewlTo-OCnTxH2WNSYAOU';

const ASSOCIATES_SHEET_NAME = 'ASSOCIATI';
const LOG_SHEET_NAME = 'NOTULE';
const SETTINGS_SHEET_NAME = 'IMPOSTAZIONI_QUOTE';
const QUOTE_SHEET_NAME = 'QUOTE';
const ISCRIZIONI_SHEET_NAME = 'ISCRIZIONI';
const TEMPLATE_SHEET_NAME = 'TEMPLATE';

/** 1-based column number for first annual-quota column on ASSOCIATI (col S) */
const START_COL_QUOTE = 19;

const COL_INDEX = {
  NUMERO_ASSOCIATO: 0,
  DATA_ISCRIZIONE: 1,
  NOME: 3,
  COGNOME: 4,
  LUOGO_NASCITA: 5,
  PROVINCIA_NASCITA: 6,
  DATA_NASCITA: 7,
  INDIRIZZO: 8,
  CAP: 9,
  CITTA: 10,
  PROVINCIA_RESIDENZA: 11,
  CODICE_FISCALE: 12,
  TELEFONO: 13,
  EMAIL: 14,
  NUMERO_TUTORE: 15,
  NOME_COMPLETO_TUTORE: 16,
  TUTORE_NOME_MANUALE: 17,
  TUTORE_COGNOME_MANUALE: 18,
  TUTORE_CELLULARE_MANUALE: 19,
  TUTORE_EMAIL_MANUALE: 20,
  TUTORE_CF_MANUALE: 21,
  TELEGRAM_CHAT_ID: 22,
  CONSENSO_GDPR: 23,
};

const LOG_COL_INDEX = {
  ANNO: 0,
  DATA_GENERAZIONE: 1,
  PROGRESSIVO: 2,
  IMPORTO_LORDO: 3,
  RITENUTA: 4,
  IMPORTO_NETTO: 5,
  NOME_ASSOCIATO: 6,
  URL_PDF: 7,
  METODO_PAGAMENTO: 8,
  DATA_PAGAMENTO: 9,
  IMPORTO_RICEVUTE: 10,
  RICEVUTE: 11,
};

const ISCR_COL = {
  ID: 0,
  NOME: 1,
  COGNOME: 2,
  EMAIL: 3,
  CF: 4,
  TELEFONO: 5,
  ANNO_SOCIETARIO: 6,
  IMPORTO_CENTESIMI: 7,
  PAGAMENTO_STATO: 8,
  PAGAMENTO_LINK_URL: 9,
  PAGAMENTO_LINK_ID: 10,
  PAGAMENTO_TOTALE_CENTESIMI: 11,
  PAGAMENTO_STRIPE_LORDO: 12,
  PAGAMENTO_STRIPE_FEE: 13,
  PAGAMENTO_STRIPE_NETTO: 14,
  PAGAMENTO_STRIPE_PI: 15,
  PAGAMENTO_PAGATO_AT: 16,
  CREATED_AT: 17,
  PAYLOAD_JSON: 18,
  PDF_URL: 19,
  EMAIL_CONFERMA_INVIATA: 20,
};

const TIMEZONE = 'Europe/Rome';

module.exports = {
  SPREADSHEET_ID,
  ASSOCIATES_SHEET_NAME,
  LOG_SHEET_NAME,
  SETTINGS_SHEET_NAME,
  QUOTE_SHEET_NAME,
  ISCRIZIONI_SHEET_NAME,
  TEMPLATE_SHEET_NAME,
  START_COL_QUOTE,
  COL_INDEX,
  LOG_COL_INDEX,
  ISCR_COL,
  TIMEZONE,
};
